In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [2]:
features = pd.read_csv("features.txt",sep=",")

In [3]:
df = pd.read_csv("kdd10.csv", names = features.columns)
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack_type
0,0,tcp,http,SF,181,5450,0,0,0,0,...,9,1.0,0.0,0.11,0.0,0.0,0.0,0.0,0.0,normal.
1,0,tcp,http,SF,239,486,0,0,0,0,...,19,1.0,0.0,0.05,0.0,0.0,0.0,0.0,0.0,normal.
2,0,tcp,http,SF,235,1337,0,0,0,0,...,29,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
3,0,tcp,http,SF,219,1337,0,0,0,0,...,39,1.0,0.0,0.03,0.0,0.0,0.0,0.0,0.0,normal.
4,0,tcp,http,SF,217,2032,0,0,0,0,...,49,1.0,0.0,0.02,0.0,0.0,0.0,0.0,0.0,normal.

In [4]:
df = df.reset_index()

In [5]:
df['attack_type'] = df["attack_type"].astype('category')
df['attack_type'] = df['attack_type'].cat.codes
df['attack_type'] = df["attack_type"].astype('int64')

In [6]:
dummies = pd.get_dummies(df['protocol_type'], drop_first='True')
df = pd.concat([df, dummies], axis=1)
df.drop(['protocol_type'], inplace=True, axis=1)

dummies = pd.get_dummies(df['service'], drop_first='True')
df = pd.concat([df, dummies], axis=1)
df.drop(['service'], inplace=True, axis=1)

dummies = pd.get_dummies(df['flag'], drop_first='True')
df = pd.concat([df, dummies], axis=1)
df.drop(['flag'], inplace=True, axis=1)
df.head()

,index,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,...,REJ,RSTO,RSTOS0,RSTR,S0,S1,S2,S3,SF,SH
0,0,0,181,5450,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
1,1,0,239,486,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
2,2,0,235,1337,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
3,3,0,219,1337,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
4,4,0,217,2032,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0

In [7]:
X = df.drop(columns=['attack_type'],axis=1)
y = df['attack_type']

X = X.fillna(X.mean())

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [10]:
glf = GaussianNB()
glf.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [11]:
pred = glf.predict(X_test)

In [12]:
from sklearn.metrics import classification_report,confusion_matrix

import sys
sys.path.append('/usr/local/lib/python2.7/dist-packages')
import seaborn as sns

In [15]:
# sns.heatmap(confusion_matrix(pred,y_test),cmap='coolwarm')
print(classification_report(pred,y_test))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97       619
           1       0.64      0.05      0.09       142
           2       1.00      0.01      0.02       124
           3       0.83      0.91      0.87        11
           4       0.00      0.00      0.00        28
           5       1.00      0.15      0.26      2590
           6       0.00      0.00      0.00         0
           7       0.50      0.00      0.00       478
           8       0.00      0.00      0.00        24
           9       1.00      0.96      0.98     33380
          10       0.08      0.01      0.01       777
          11       0.77      0.99      0.87     22606
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00        10
          14       0.98      0.26      0.41       228
          15       0.09      0.09      0.09       347
          16       0.50      0.00      0.01       217
          17       0.81      0.99      0.89       380
          18       1.00      1.00      1.00     84307
          20       0.12      0.02      0.04      1626
          21       0.14      0.15      0.14       301
          22       1.00      0.58      0.74        12

   micro avg       0.95      0.95      0.95    148207
   macro avg       0.52      0.33      0.34    148207
weighted avg       0.94      0.95      0.93    148207